//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.296
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GCI.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o vuelva a generar su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GCI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap _585x285_A {
            get {
                object obj = ResourceManager.GetObject("585x285_A", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap arrow_bottom_icon_16 {
            get {
                object obj = ResourceManager.GetObject("arrow_bottom_icon&16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap arrow_bottom_icon_161 {
            get {
                object obj = ResourceManager.GetObject("arrow_bottom_icon&161", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap arrow_right_icon_16 {
            get {
                object obj = ResourceManager.GetObject("arrow_right_icon&16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap book_icon_16 {
            get {
                object obj = ResourceManager.GetObject("book_icon&16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap book_icon_161 {
            get {
                object obj = ResourceManager.GetObject("book_icon&161", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bookmark_1_icon_16 {
            get {
                object obj = ResourceManager.GetObject("bookmark_1_icon&16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bookmark_2_icon_16 {
            get {
                object obj = ResourceManager.GetObject("bookmark_2_icon&16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap box_icon_16 {
            get {
                object obj = ResourceManager.GetObject("box_icon&16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap calendar_1_icon_16 {
            get {
                object obj = ResourceManager.GetObject("calendar_1_icon&16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cancel_icon_16 {
            get {
                object obj = ResourceManager.GetObject("cancel_icon&16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cancel_icon_161 {
            get {
                object obj = ResourceManager.GetObject("cancel_icon&161", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cc_icon_16 {
            get {
                object obj = ResourceManager.GetObject("cc_icon&16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cert_icon_16 {
            get {
                object obj = ResourceManager.GetObject("cert_icon&16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap chart_bar_icon_16 {
            get {
                object obj = ResourceManager.GetObject("chart_bar_icon&16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap chart_pie_icon_16 {
            get {
                object obj = ResourceManager.GetObject("chart_pie_icon&16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap chat_bubble_message_square_icon_16 {
            get {
                object obj = ResourceManager.GetObject("chat_bubble_message_square_icon&16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap checkbox_checked_icon_16 {
            get {
                object obj = ResourceManager.GetObject("checkbox_checked_icon&16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap checkmark_icon_16 {
            get {
                object obj = ResourceManager.GetObject("checkmark_icon&16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap contact_card_icon_16 {
            get {
                object obj = ResourceManager.GetObject("contact_card_icon&16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap doc_delete_icon_16 {
            get {
                object obj = ResourceManager.GetObject("doc_delete_icon&16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap doc_edit_icon_16 {
            get {
                object obj = ResourceManager.GetObject("doc_edit_icon&16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap doc_lines_icon_16 {
            get {
                object obj = ResourceManager.GetObject("doc_lines_icon&16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap doc_new_icon_16 {
            get {
                object obj = ResourceManager.GetObject("doc_new_icon&16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap eye_inv_icon_16 {
            get {
                object obj = ResourceManager.GetObject("eye_inv_icon&16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap filter_icon_16 {
            get {
                object obj = ResourceManager.GetObject("filter_icon&16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Fondo {
            get {
                object obj = ResourceManager.GetObject("Fondo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Fondo_A {
            get {
                object obj = ResourceManager.GetObject("Fondo_A", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Fondo_B {
            get {
                object obj = ResourceManager.GetObject("Fondo_B", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Fondo_D {
            get {
                object obj = ResourceManager.GetObject("Fondo D", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Fondo_Final {
            get {
                object obj = ResourceManager.GetObject("Fondo Final", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Fondo_Final1 {
            get {
                object obj = ResourceManager.GetObject("Fondo Final1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Fondo_Final2 {
            get {
                object obj = ResourceManager.GetObject("Fondo Final2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Fondo_Final3 {
            get {
                object obj = ResourceManager.GetObject("Fondo Final3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Fondo_Final4 {
            get {
                object obj = ResourceManager.GetObject("Fondo Final4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Fondo_principal {
            get {
                object obj = ResourceManager.GetObject("Fondo principal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap font_italic_icon_16 {
            get {
                object obj = ResourceManager.GetObject("font_italic_icon&16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap font_strokethrough_icon_16 {
            get {
                object obj = ResourceManager.GetObject("font_strokethrough_icon&16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap globe_1_icon_16 {
            get {
                object obj = ResourceManager.GetObject("globe_1_icon&16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap globe_2_icon_16 {
            get {
                object obj = ResourceManager.GetObject("globe_2_icon&16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap globe_3_icon_16 {
            get {
                object obj = ResourceManager.GetObject("globe_3_icon&16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap home_icon_16 {
            get {
                object obj = ResourceManager.GetObject("home_icon&16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap key_icon_16 {
            get {
                object obj = ResourceManager.GetObject("key_icon&16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap logo_final_48 {
            get {
                object obj = ResourceManager.GetObject("logo_final&48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mail_2_icon_16 {
            get {
                object obj = ResourceManager.GetObject("mail_2_icon&16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mail_2_icon_161 {
            get {
                object obj = ResourceManager.GetObject("mail_2_icon&161", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mail_icon_16 {
            get {
                object obj = ResourceManager.GetObject("mail_icon&16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap money_icon_16 {
            get {
                object obj = ResourceManager.GetObject("money_icon&16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap notepad_icon_16 {
            get {
                object obj = ResourceManager.GetObject("notepad_icon&16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap on_off_icon_16 {
            get {
                object obj = ResourceManager.GetObject("on-off_icon&16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap page_layout_icon_16 {
            get {
                object obj = ResourceManager.GetObject("page_layout_icon&16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap page_layout_icon_161 {
            get {
                object obj = ResourceManager.GetObject("page_layout_icon&161", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap phone_2_icon_16 {
            get {
                object obj = ResourceManager.GetObject("phone_2_icon&16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap phone_icon_16 {
            get {
                object obj = ResourceManager.GetObject("phone_icon&16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pin_map_down_icon_16 {
            get {
                object obj = ResourceManager.GetObject("pin_map_down_icon&16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pin_map_icon_16 {
            get {
                object obj = ResourceManager.GetObject("pin_map_icon&16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap print_icon_16 {
            get {
                object obj = ResourceManager.GetObject("print_icon&16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap reload_icon_16 {
            get {
                object obj = ResourceManager.GetObject("reload_icon&16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap round_checkmark_icon_16 {
            get {
                object obj = ResourceManager.GetObject("round_checkmark_icon&16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap round_minus_icon_16 {
            get {
                object obj = ResourceManager.GetObject("round_minus_icon&16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap save_icon_16 {
            get {
                object obj = ResourceManager.GetObject("save_icon&16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap trama_comprobantes_48 {
            get {
                object obj = ResourceManager.GetObject("trama_comprobantes&48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap user_icon_16 {
            get {
                object obj = ResourceManager.GetObject("user_icon&16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap users_icon_16 {
            get {
                object obj = ResourceManager.GetObject("users_icon&16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wallet_icon_16 {
            get {
                object obj = ResourceManager.GetObject("wallet_icon&16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wrench_icon_16 {
            get {
                object obj = ResourceManager.GetObject("wrench_icon&16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wrench_plus_2_icon_16 {
            get {
                object obj = ResourceManager.GetObject("wrench_plus_2_icon&16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wrench_plus_icon_16 {
            get {
                object obj = ResourceManager.GetObject("wrench_plus_icon&16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap youtube_icon_16 {
            get {
                object obj = ResourceManager.GetObject("youtube_icon&16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
