//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace Modelo_Entidades
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class GCI_AuditoriaContainer : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto GCI_AuditoriaContainer usando la cadena de conexión encontrada en la sección 'GCI_AuditoriaContainer' del archivo de configuración de la aplicación.
        /// </summary>
        public GCI_AuditoriaContainer() : base("name=GCI_AuditoriaContainer", "GCI_AuditoriaContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto GCI_AuditoriaContainer.
        /// </summary>
        public GCI_AuditoriaContainer(string connectionString) : base(connectionString, "GCI_AuditoriaContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto GCI_AuditoriaContainer.
        /// </summary>
        public GCI_AuditoriaContainer(EntityConnection connection) : base(connection, "GCI_AuditoriaContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Auditoria_Log> Auditorias_Log
        {
            get
            {
                if ((_Auditorias_Log == null))
                {
                    _Auditorias_Log = base.CreateObjectSet<Auditoria_Log>("Auditorias_Log");
                }
                return _Auditorias_Log;
            }
        }
        private ObjectSet<Auditoria_Log> _Auditorias_Log;

        #endregion

        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Auditorias_Log. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToAuditorias_Log(Auditoria_Log auditoria_Log)
        {
            base.AddObject("Auditorias_Log", auditoria_Log);
        }

        #endregion

    }

    #endregion

    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="GCI_Auditoria", Name="Auditoria_Log")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Auditoria_Log : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Auditoria_Log.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad id.</param>
        /// <param name="usuario">Valor inicial de la propiedad usuario.</param>
        /// <param name="fecha">Valor inicial de la propiedad fecha.</param>
        /// <param name="accion">Valor inicial de la propiedad accion.</param>
        public static Auditoria_Log CreateAuditoria_Log(global::System.Int32 id, global::System.String usuario, global::System.DateTime fecha, global::System.String accion)
        {
            Auditoria_Log auditoria_Log = new Auditoria_Log();
            auditoria_Log.id = id;
            auditoria_Log.usuario = usuario;
            auditoria_Log.fecha = fecha;
            auditoria_Log.accion = accion;
            return auditoria_Log;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String usuario
        {
            get
            {
                return _usuario;
            }
            set
            {
                OnusuarioChanging(value);
                ReportPropertyChanging("usuario");
                _usuario = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("usuario");
                OnusuarioChanged();
            }
        }
        private global::System.String _usuario;
        partial void OnusuarioChanging(global::System.String value);
        partial void OnusuarioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime fecha
        {
            get
            {
                return _fecha;
            }
            set
            {
                OnfechaChanging(value);
                ReportPropertyChanging("fecha");
                _fecha = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fecha");
                OnfechaChanged();
            }
        }
        private global::System.DateTime _fecha;
        partial void OnfechaChanging(global::System.DateTime value);
        partial void OnfechaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String accion
        {
            get
            {
                return _accion;
            }
            set
            {
                OnaccionChanging(value);
                ReportPropertyChanging("accion");
                _accion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("accion");
                OnaccionChanged();
            }
        }
        private global::System.String _accion;
        partial void OnaccionChanging(global::System.String value);
        partial void OnaccionChanged();

        #endregion

    
    }

    #endregion

    
}
